apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: etcd-monitoring-svc
  name: etcd-monitoring-svc
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 4001
      protocol: TCP
      targetPort: 4001
  selector:
    k8s-app: etcd-manager-main
  sessionAffinity: None
  type: ClusterIP
